### PR TITLE
Add pretty formatting

### PR DESCRIPTION
**Pull request by pronebird**
This PR pads/aligns columns in formatted output.

### CODE REVIEW

**Comment by ericmartel** [comment]
Hey @pronebird 

That's pretty cool, but would it be possible for you to update it so that it only applies the padding if an option is set?

Thanks

**Comment by pronebird** [comment]
@ericmartel like a sublime setting? Sure thing!

**Comment by ericmartel** [comment]
Thinking about it I think it might require a new command... I don't think this mixes well with formatting text, like:

I'm outputting the first column {0} followed by the 5th! {4}

The spaces wouldn't work in that case...

I feel like what you want is a dump table with fixed column width?

**Comment by pronebird** [comment]
Precisely what I am trying to replicate, but the order does not really matter since we count max length for each column and then pad output for each column matching `{#}` pattern.

New command sounds like a good idea actually!

**Comment by pronebird** [comment]
Closing due to absence of interest in proceeding with this PR.

**Pull request closed without merging**
